Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2023-12, with the labels that each got.

#8867 Reassign throttling guidance to docs v-team
  concepts/throttling.md
Labels: ready to merge

#8870 Fix #8858 - note about `me` = delegated
  concepts/auth/auth-concepts.md
Labels: area: authentication, area: Entra, ready to merge

#8900 Update application-post-onlinemeetings.md
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
Labels: ready to merge

#8744 Update subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: area: change notifications, area: Entra, ready to merge
