Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2023-11, with the labels that each got.

#8776 Remove example 4 per PM.
  api-reference/beta/api/synchronization-synchronizationjob-post-bulkupload.md
Labels: content review complete, ready to merge

#8782 Removes deprecated DELETE reference.
  api-reference/beta/resources/synchronization-bulkupload.md
Labels: ready for content review, ready to merge

#8793 Fix customer issues
  api-reference/beta/api/recommendation-tenantsecurescores.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md
Labels: area: Entra, ready to merge

#8750 Fix Graph API AppID
  api-reference/beta/api/application-addkey.md
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/application-addkey.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
Labels: review requested

#8818 Fix snippet generation for block
  api-reference/v1.0/api/intune-deviceconfig-devicecompliancepolicy-scheduleactionsforrules.md
Labels: ready to merge

#8836 [minor] Move space outside of code marker
  api-reference/v1.0/resources/socialidentityprovider.md
Labels: ready to merge

#8837 Update userregistrationdetails.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/v1.0/resources/userregistrationdetails.md
Labels: ready to merge

#8820 Adding roles allowed to add a federation configuration
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/includes/rbac-for-apis/rbac-domainfederation-apis-write.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/includes/rbac-for-apis/rbac-domainfederation-apis-write.md
Labels: area: Entra, content review complete, ready to merge

#8785 Add Search schema known limitation for Graph Search API
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  concepts/search-concept-files.md
Labels: ready to merge, review feedback addressed

#8855 Update permissions-management-api-overview.md
  api-reference/beta/resources/permissions-management-api-overview.md
Labels: area: Entra, ready to merge

#8852 Update user-sendmail.md
  api-reference/beta/api/user-sendmail.md
  api-reference/v1.0/api/user-sendmail.md
Labels: ready to merge, review feedback addressed
