Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2023-08, with the labels that each got.

#920 Update educationclass-post-teachers.md
  api-reference/v1.0/api/educationclass-post-teachers.md
Labels: do not merge

#919 Update educationclass-post-teachers.md
  api-reference/beta/api/educationclass-post-teachers.md
Labels: do not merge

#1004 Recreated changes from closed PR
  api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge

#1020 Update educationassignmentsettings-update.md
  api-reference/beta/api/educationassignmentsettings-update.md
Labels: do not merge

#1021 Update educationassignmentsettings-update.md
  api-reference/v1.0/api/educationassignmentsettings-update.md
Labels: do not merge

#1007 Added custom Hosts to MGT Providers
  concepts/toolkit/providers/msal2.md
  concepts/toolkit/providers/providers.md
Labels: content review complete, ready to merge, review requested

#8414 Fixes hyperlink
  concepts/json-batching.md
Labels: do not merge

#8419 Update group.md
  api-reference/v1.0/resources/group.md
Labels: do not merge

#8420 Update group.md
  api-reference/beta/resources/group.md
Labels: do not merge

#8428 - fixes top being present in next links
  concepts/paging.md
Labels: do not merge, ready for content review, review requested

#8434 Typo fixes
  concepts/windowsupdates-deploy-expedited-update.md
Labels: ready for content review

#927 Update mgdc overview
  concepts/data-connect-concept-overview.md
  concepts/images/data-connect-continuing-growth.png
  concepts/images/data_connect_logo_gainx.png
  concepts/images/data_connect_logo_gjpepsi.png
  concepts/images/data_connect_logo_hclsoftware.png
  concepts/images/data_connect_logo_infosys.png
  concepts/images/data_connect_logo_jll.png
  concepts/images/data_connect_logo_lotis_blue.png
  concepts/images/data_connect_logo_neo4j.png
  concepts/images/data_connect_logo_neudesic.png
  concepts/images/data_connect_logo_parabole.png
  concepts/images/data_connect_logo_politecnico.png
  concepts/images/data_connect_logo_sura.png
  concepts/images/data_connect_logo_tata_cs.png
  concepts/images/data_connect_logo_veldhoen.png
  concepts/images/data_connect_logo_wipro.png
  concepts/images/data_connect_microsoft_fabric.png
  concepts/images/data_connect_msdc_solution.png
  concepts/images/data_connect_why_choose_mgdc.png
Labels: content review complete, ready to merge

#8440 Update security-ediscoveryreviewset-export.md
  api-reference/v1.0/api/security-ediscoveryreviewset-export.md
Labels: ready to merge

#8450 Update security-ediscoveryreviewsetquery-export.md
  api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
Labels: ready to merge

#8454 Fix broken link and typo in docs
  concepts/toolkit/components/person.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
Labels: do not merge

#8460 Fix typo in entity.md
  api-reference/v1.0/resources/entity.md
Labels: do not merge

#8459 Updated main error page.
  concepts/errors.md
Labels: do not merge

#8465 Corrected description of webUrl property
  api-reference/beta/resources/baseitem.md
  api-reference/v1.0/resources/baseitem.md
Labels: area: onedrive, ready to merge

#8473 Fix a couple of dead links to sample apps
  concepts/toolkit/providers/electron.md
  concepts/toolkit/providers/proxy.md
Labels: do not merge

#8486 Update the graph doc for the publicationFacet new properties
  api-reference/beta/resources/publicationfacet.md
  api-reference/v1.0/resources/publicationfacet.md
  changelog/Microsoft.FileServices.json
Labels: ready for content review

#8499 Update group-post-members.md
  api-reference/beta/api/group-post-members.md
Labels: do not merge

#8504 Update deviceregistrationpolicy.md
  api-reference/beta/resources/deviceregistrationpolicy.md
Labels: ready to merge
