Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2023-09, with the labels that each got.

#8476 Update learningselfinitiatedcourse.md
  api-reference/beta/resources/learningselfinitiatedcourse.md
Labels: do not merge

#8477 Update learningselfinitiatedcourse.md
  api-reference/v1.0/resources/learningselfinitiatedcourse.md
Labels: do not merge

#8481 Update admin.md
  api-reference/v1.0/resources/admin.md
Labels: do not merge

#8482 Update user.md
  api-reference/beta/resources/user.md
Labels: do not merge

#8483 Update organizationsettings-list-peopleinsights.md
  api-reference/beta/api/organizationsettings-list-peopleinsights.md
Labels: do not merge

#8484 Update insightssettings-update.md
  api-reference/beta/api/insightssettings-update.md
Labels: do not merge

#8485 Update universal-print-concept-overview.md
  concepts/images/universal-print-portal-homepage.png
Labels: do not merge

#8496 Update accessreviewsv2-overview.md
  api-reference/beta/resources/accessreviewsv2-overview.md
Labels: do not merge

#8501 Update unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
Labels: do not merge

#8502 Update unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
Labels: do not merge

#8512 Update virtualeventwebinar.md
  api-reference/beta/resources/virtualeventwebinar.md
Labels: do not merge

#8513 Update toc.yml
  api-reference/beta/toc.yml
Labels: do not merge

#8514 Update virtualeventregistrant.md
  api-reference/beta/resources/virtualeventregistrant.md
Labels: do not merge

#8515 Update virtualeventregistrant-get.md
  api-reference/beta/api/virtualeventregistrant-get.md
Labels: do not merge

#8516 Update virtualeventwebinar-get.md
  api-reference/beta/api/virtualeventwebinar-get.md
Labels: do not merge

#8523 Update throttling-limits.md
  concepts/throttling-limits.md
Labels: do not merge

#8531 Update Group (Directory) Settings page
  concepts/group-directory-settings.md
Labels: area: Entra, content review complete, ready to merge

#8535 Update device.md
  api-reference/v1.0/resources/device.md
Labels: do not merge

#8542 Update educationcategory-get.md
  api-reference/beta/api/educationcategory-get.md
Labels: do not merge

#8543 Update educationcategory-get.md
  api-reference/v1.0/api/educationcategory-get.md
Labels: do not merge

#8544 Update educationrubric-get.md
  api-reference/v1.0/api/educationrubric-get.md
Labels: do not merge

#8545 Update educationrubric-get.md
  api-reference/beta/api/educationrubric-get.md
Labels: do not merge

#8623 Add statement that period parameter is mandatory for relyingpartydetailedsummary-list by cewu.md
  api-reference/beta/api/relyingpartydetailedsummary-list.md
Labels: ready for content review

#8603 Update throttling-limits.md
  concepts/throttling-limits.md
Labels: do not merge

#8626 Update driveitem-search.md
  api-reference/beta/api/driveitem-search.md
  api-reference/v1.0/api/driveitem-search.md
Labels: do not merge

#8595 Correcting the query that is missing a '?' for the 'filter' parameter
  api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
Labels: do not merge

#8588 Update verb from PATCH to PUT for Stream type in Example 2
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/v1.0/api/organizationalbranding-update.md
  api-reference/v1.0/api/organizationalbrandinglocalization-update.md
Labels: area: Entra, content review complete, ready to merge

#8592 Update teamsapp-update.md
  api-reference/v1.0/api/teamsapp-update.md
Labels: do not merge

#8591 Update teamsapp-update.md
  api-reference/beta/api/teamsapp-update.md
Labels: do not merge

#8590 Update teamsapp-publish.md
  api-reference/beta/api/teamsapp-publish.md
Labels: do not merge

#8589 Update teamsapp-publish.md
  api-reference/v1.0/api/teamsapp-publish.md
Labels: do not merge

#8593 Update indexing-api-overview.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/v1.0/resources/indexing-api-overview.md
Labels: do not merge

#8527 Removed reference to $expand
  api-reference/v1.0/api/bookingbusiness-list.md
Labels: do not merge

#8528 Removed reference to $expand
  api-reference/v1.0/api/bookingbusiness-get.md
Labels: do not merge

#8553 Update educationuser-list-classes.md
  api-reference/beta/api/educationuser-list-classes.md
Labels: do not merge

#8554 Update educationuser-list-classes.md
  api-reference/v1.0/api/educationuser-list-classes.md
Labels: do not merge

#8629 Updating status keyword in the CompanySubscription API document
  api-reference/beta/resources/companysubscription.md
Labels: area: Entra, content review complete, ready to merge

#8555 Update educationuser-get.md
  api-reference/beta/api/educationuser-get.md
Labels: do not merge

#8556 Update educationuser-get.md
  api-reference/v1.0/api/educationuser-get.md
Labels: do not merge

#8557 Update educationclass-post-category.md
  api-reference/v1.0/api/educationclass-post-category.md
Labels: do not merge

#8558 Update educationclass-post-category.md
  api-reference/beta/api/educationclass-post-category.md
Labels: do not merge

#8560 Update educationclass-list-members.md
  api-reference/v1.0/api/educationclass-list-members.md
Labels: do not merge

#8563 Update educationclass-delete-teachers.md
  api-reference/v1.0/api/educationclass-delete-teachers.md
Labels: do not merge

#8564 Update educationclass-delete-teachers.md
  api-reference/beta/api/educationclass-delete-teachers.md
Labels: do not merge

#8571 Update custom-connector-sdk-overview.md
  concepts/custom-connector-sdk-overview.md
Labels: do not merge

#8643 Update subscription.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
Labels: area: change notifications, ready to merge

#8641 Update add-properties-profilecard.md
  concepts/add-properties-profilecard.md
Labels: do not merge

#8636 Fix `Identityt` typo
  concepts/permissions-reference.md
Labels: do not merge

#8500 add knwon issues for query template
  concepts/search-concept-query-template.md
Labels: ready to merge, review feedback addressed

#8559 Update educationclass-list-members.md
  api-reference/beta/api/educationclass-list-members.md
Labels: do not merge

#8509 Get bearer token detail
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: ready to merge
