Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2023-10, with the labels that each got.

#8708 [MGDC] Add more details to self-serve migration docs
  concepts/existing-customer-migration.md
Labels: content review complete

#8716 Update team-post.md
  api-reference/beta/api/team-post.md
  api-reference/v1.0/api/team-post.md
Labels: ready to merge

#8703 Update throttling-limits.md
  concepts/throttling-limits.md
  includes/throttling-subscription-services.md
Labels: area: change notifications, area: Entra, content review complete

#8706 Update docs: Update profilePhoto
  api-reference/beta/api/profilephoto-update.md
  api-reference/v1.0/api/profilephoto-update.md
Labels: conflicting, content review complete, ready to merge

#8573 Update subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: area: change notifications, area: Entra, content review complete, ready to merge

#8574 Update subscription-post-subscriptions.md
  api-reference/beta/api/subscription-post-subscriptions.md
Labels: area: change notifications, area: Entra, content review complete, ready to merge

#8575 Patch 3
  concepts/change-notifications-delivery-event-hubs.md
  concepts/change-notifications-delivery-webhooks.md
Labels: area: change notifications, area: Entra, content review complete, ready to merge

#8727 Update user-post-events.md
  api-reference/beta/api/user-post-events.md
  api-reference/v1.0/api/user-post-events.md
Labels: ready to merge

#8550 Update presence-setpresence.md
  api-reference/beta/api/presence-setpresence.md
  api-reference/v1.0/api/presence-setpresence.md
Labels: do not merge

#8621 Testing fix to breadcrumb by adding Learn at first level
  concepts/breadcrumb/toc.yml
Labels: ready for content review

#8736 Fix link for Microsoft Forms Usage on report.md
  api-reference/beta/resources/report.md
Labels: ready for content review

#8759 Update sdks-overview.md
  concepts/sdks/sdks-overview.md
Labels: area: SDKs, content review complete, ready to merge

#8756 Update team-post.md SPO provision
  api-reference/beta/api/team-post.md
  api-reference/v1.0/api/team-post.md
Labels: content review complete, customer support issue

#8754 Update channel-post.md SPO provision
  api-reference/beta/api/channel-post.md
  api-reference/v1.0/api/channel-post.md
Labels: content review complete, customer support issue
