Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-01, with the labels that each got.

#8998 Update TOC to remove CLI preview
  concepts/toc.yml
Labels: ready for content review

#9006 Update security-emailthreatsubmission-post-emailthreats.md to fix odata.type namespace issue
  api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
Labels: ready to merge

#9042 Update throttling overview metadata
  concepts/throttling.md
Labels: do not merge, ready to merge

#9029 Update notes for Directory.ReadWrite.All
  includes/permissions-notes/directory.readwrite.all.md
Labels: area: Entra, content review complete, ready to merge

#9045 Update permissions-grant-via-msgraph.md
  concepts/permissions-grant-via-msgraph.md
Labels: area: app model, area: Entra, content review complete, ready to merge

#9061 Fix typo in remoteItem.md
  api-reference/beta/resources/remoteitem.md
  api-reference/v1.0/resources/remoteitem.md
Labels: ready to merge
