Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-06, with the labels that each got.

#9248 Update invitation-post.md
  api-reference/beta/api/invitation-post.md
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/invitation.md
Labels: area: Entra, content review complete, ready to merge

#9360 working elsewhere is 0, not 4
  api-reference/beta/resources/scheduleinformation.md
  api-reference/v1.0/resources/scheduleinformation.md
Labels: ready to merge

#9363 Add notes for print troubleshooting and conditions around updating printer share
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/beta/api/printershare-update.md
  api-reference/v1.0/api/printer-post-jobs.md
  api-reference/v1.0/api/printershare-post-jobs.md
  api-reference/v1.0/api/printershare-update.md
  concepts/upload-data-to-upload-session.md
Labels: content review complete, ready to merge

#9362 Update onlinemeeting.md - changed List to List recordings
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: ready to merge

#9361 Update itemreference.md
  api-reference/beta/resources/itemreference.md
  api-reference/v1.0/resources/itemreference.md
Labels: ready to merge

#9191 Documentation update for isFavoriteByDefault
  api-reference/beta/resources/channel.md
  api-reference/v1.0/resources/channel.md
  changelog/Microsoft.Teams.Core.json
Labels: content review complete, ready to merge, resolved: awaiting prod deployment

#9358 Fabric OneLake as a sink.md
  concepts/data-connect-datasets.md
Labels: ready to merge

#9364 Update userregistrationdetails.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/v1.0/resources/userregistrationdetails.md
Labels: ready to merge

#9365 Update accessreviewsv2-overview.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
Labels: review feedback addressed

#9371 Update throttling-limits.md
  concepts/throttling-limits.md
Labels: ready to merge

#9372 Fix typo "demostrate" -> "demonstrate"
  concepts/application-rollkey-prooftoken.md
Labels: ready to merge

#9353 Add more specific administrator language
  api-reference/beta/api/subscription-list.md
  api-reference/v1.0/api/subscription-list.md
Labels: area: change notifications, area: Entra, content review in progress, ready to merge

#9374 fix: wrong endpoint version for documentation page
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-get.md
Labels: ready for content review
