Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-08, with the labels that each got.

#9401 Update profile photo update permissions.
  api-reference/beta/api/profilephoto-delete.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/v1.0/api/profilephoto-delete.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
Labels: content review complete, ready to merge

#9404 Update bookingschedulingpolicy.md
  api-reference/beta/resources/bookingschedulingpolicy.md
  api-reference/v1.0/resources/bookingschedulingpolicy.md
Labels: customer support issue, ready to merge

#9408 Update devicelocalcredentialinfo-get.md
  api-reference/beta/api/devicelocalcredentialinfo-get.md
  api-reference/beta/api/directory-list-devicelocalcredentials.md
  changelog/Microsoft.DeviceLocalCredentials.json
Labels: area: Entra, content review complete, ready to merge

#9409 Update serviceprincipal.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: area: app model, area: Entra, ready to merge
