Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-12, with the labels that each got.

#9471 Update examples for correct endUserNotification schema when creating Attack Simulation
  api-reference/beta/api/attacksimulationroot-post-simulation.md
  api-reference/beta/includes/snippets/powershell/create-simulations-powershell-snippets.md
  api-reference/v1.0/api/attacksimulationroot-post-simulation.md
  api-reference/v1.0/includes/snippets/powershell/create-simulations-powershell-snippets.md
Labels: bug: documentation, content review complete

#9473 Correct example url for GET of Payload in AST
  api-reference/beta/api/payload-get.md
  api-reference/beta/api/payloaddetail-get.md
  api-reference/v1.0/api/payload-get.md
  api-reference/v1.0/api/payloaddetail-get.md
Labels: bug: documentation, content review complete

#9474 Update to include phishTraining as a possible simulation technique value
  api-reference/beta/api/attacksimulationroot-post-simulation.md
  api-reference/beta/api/simulation-update.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/simulation.md
Labels: bug: documentation, content review complete

#9477 Update intune-shared-deviceappmanagement-get.md
  api-reference/beta/api/intune-shared-deviceappmanagement-get.md
Labels: bug: documentation, content review complete

#9476 Update profile.md
  api-reference/beta/resources/profile.md
Labels: content review complete, ready to merge

#9478 fix: removes extraneous beta disclamer
  api-reference/v1.0/resources/authenticationmethods-usage-insights-overview.md
Labels: content review complete, ready to merge

#9479 Configure administrator support for profile photo updates
  concepts/profilephoto-configure-settings.md
Labels: content review complete

#9480 Update best-practices-concept.md
  concepts/best-practices-concept.md
Labels: review feedback addressed

#9486 Update event-delta.md
  api-reference/v1.0/api/event-delta.md
Labels: content review in progress
