Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-04, with the labels that each got.

#9305 Update driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
Labels: ready to merge

#9306 Update connectors-api-overview.md
  api-reference/beta/resources/connectors-api-overview.md
  api-reference/v1.0/resources/connectors-api-overview.md
Labels: ready to merge

#9292 Use correct argument for Get-Content to return bytes
  concepts/applications-how-to-add-certificate.md
Labels: area: applications, area: Entra, content review complete, ready to merge

#9310 Update planner-concept-overview.md
  concepts/planner-concept-overview.md
Labels: ready to merge

#9314 Update max number of listeners
  api-reference/beta/resources/authenticationeventlistener.md
  api-reference/beta/resources/customauthenticationextension.md
Labels: area: Entra, content review complete, ready to merge

#9309 Update plannertask-update.md
  api-reference/beta/api/plannertask-update.md
  api-reference/v1.0/api/plannertask-update.md
Labels: ready to merge

#9316 Update Teams section ToC with calling
  concepts/toc.yml
Labels: ready for content review, ready to merge

#9317 Fix Graph API app proxy application creation sample
  concepts/application-proxy-configure-api.md
Labels: area: Entra, content review complete, ready to merge

#9323 Update directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-list.md
Labels: ready to merge

#9322 Export API getRetainedMessages update to include additional $filter params
  api-reference/beta/api/channel-getallretainedmessages.md
  api-reference/beta/api/chat-getallretainedmessages.md
Labels: ready to merge

#9327 Update throttling-limits.md
  concepts/throttling-limits.md
Labels: ready to merge

#9334 docs: add connector description details
  concepts/connecting-external-content-experiences.md
Labels: ready to merge

#9333 Update educationclass-delete-members.md - fix delete example
  api-reference/beta/api/educationclass-delete-members.md
  api-reference/v1.0/api/educationclass-delete-members.md
Labels: ready to merge
