Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-02, with the labels that each got.

#9085 Update search-query.md
  api-reference/beta/api/search-query.md
  api-reference/v1.0/api/search-query.md
Labels: ready to merge

#9093 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: ready to merge

#9102 IMP: Fix get all sites permissions
  api-reference/beta/includes/permissions/site-getallsites-permissions.md
  api-reference/v1.0/includes/permissions/site-getallsites-permissions.md
Labels: ready to merge

#9097 Corrected the method and request
  api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md
Labels: area: Entra, area: identity, content review complete, ready to merge

#9109 Updating parameters required to create a local B2C identity
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-post-users.md
Labels: area: Entra, B2C, content review complete, ready to merge

#9121 Update tutorial-lifecycle-workflows-set-employeeleavedatetime.md
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: ready to merge

#9124 Update sitecollection.md
  api-reference/beta/resources/sitecollection.md
  api-reference/v1.0/resources/sitecollection.md
Labels: content review complete, ready to merge

#9127 Include `$` character for consistency with SDK generation.
  api-reference/v1.0/api/listitem-list.md
Labels: ready to merge

#9133 Update tutorial-lifecycle-workflows-set-employeeleavedatetime.md
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: ready to merge

#9149 Update json body to fix snippet generation
  api-reference/beta/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/homerealmdiscoverypolicy-update.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-update.md
Labels: area: Entra, bug: sample, ready to merge

#9156 Warn non-migrated tenants to migrate in onboarding doc
  includes/data-connect-quickstart-01.md
Labels: ready to merge

#9138 Update schedulinggroup.md
  api-reference/beta/resources/schedulinggroup.md
Labels: ready to merge

#9137 Update timeoffreason.md
  api-reference/beta/resources/timeoffreason.md
Labels: ready to merge

#9175 Update signinactivity.md
  api-reference/beta/resources/signinactivity.md
Labels: content review complete

#9105 Update teams-licenses.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/v1.0/api/chats-getallmessages.md
  concepts/teams-licenses.md
Labels: content review complete, ready to merge
