Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-05, with the labels that each got.

#9340 Update connecting-external-content-manage-schema.md
  concepts/connecting-external-content-manage-schema.md
Labels: content review complete, ready to merge

#9345 Update driveitem-delta.md of driveItem delta for deltaExcludeParent h…
  api-reference/beta/api/driveitem-delta.md
  api-reference/v1.0/api/driveitem-delta.md
Labels: ready to merge

#9346 [Export API] mentions required retention policy
  api-reference/beta/api/channel-getallretainedmessages.md
  api-reference/beta/api/chat-getallretainedmessages.md
Labels: ready to merge

#9337 Add RoleManagement.Read.All permission for listing role assignements
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
Labels: area: Entra, area: permissions, content review complete, ready to merge

#9347 Update bookingquestionassignment.md
  api-reference/beta/resources/bookingquestionassignment.md
  api-reference/v1.0/resources/bookingquestionassignment.md
Labels: ready to merge

#9354 Removing URL encoded characters in instructions
  concepts/change-notifications-delivery-event-hubs.md
Labels: area: change notifications, area: Entra, content review complete
