Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-09, with the labels that each got.

#9414 Updated to description in AuditLogQuery
  api-reference/beta/api/security-auditcoreroot-post-auditlogqueries.md
  api-reference/beta/resources/security-auditlogquery.md
Labels: ready to merge

#9412 GroupMember.Read.All and User.ReadBasic.All as least-privileged permissions.
  concepts/permissions-overview.md
Labels: content review complete, ready to merge

#9417 Update search-concept-searchall.md
  concepts/search-concept-searchall.md
Labels: content review complete, ready to merge

#9419 Update internaldomainfederation.md
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/resources/internaldomainfederation.md
Labels: content review complete, ready to merge

#9416 Update workinghours.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/resources/workinghours.md
Labels: content review complete, ready to merge

#9421 Update reflectcheckinresponse.md
  api-reference/beta/resources/reflectcheckinresponse.md
Labels: ready for content review

#9423 domain.md: relationships do not support $expand
  api-reference/beta/resources/domain.md
  api-reference/v1.0/resources/domain.md
Labels: area: directory management, area: Entra, content review complete, ready to merge
