Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2024-07, with the labels that each got.

#9265 connectorgroup.md: add possible value
  api-reference/beta/resources/connectorgroup.md
Labels: area: app model, area: Entra, content review complete, ready to merge

#9383 Fix typos in examples in profilephoto-configure-settings.md
  concepts/profilephoto-configure-settings.md
Labels: content review complete, ready to merge

#9389 Update extensibility-overview.md
  concepts/extensibility-overview.md
Labels: area: Entra, area: extensions, content review complete, ready to merge

#9386 Add backticks around claim
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/v1.0/resources/federatedidentitycredentials-overview.md
Labels: area: Entra, content review complete, ready to merge

#9387 Fix upsert definition
  api-reference/beta/api/federatedidentitycredential-upsert.md
  api-reference/v1.0/api/federatedidentitycredential-upsert.md
Labels: area: app model, area: Entra, content review complete, ready to merge

#9384 Fix typo in teams-changenotifications-callrecording-and-calltranscript.md
  concepts/teams-changenotifications-callrecording-and-calltranscript.md
Labels: ready to merge

#9395 Updated todo.md
  concepts/toolkit/components/todo.md
Labels: ready to merge, review requested

#9399 Minor doc fixes
  api-reference/beta/resources/passwordcredential.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/toc/toc.mapping.json
  api-reference/v1.0/resources/passwordcredential.md
  api-reference/v1.0/resources/unifiedroleassignment.md
Labels: area: Entra, ready to merge
