Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-07, with the labels that each got.

#9589 Update user-post-users.md forceChangePasswordNextSignIn is working …
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-post-users.md
Labels: area: Entra, area: users, awaiting internal response, ExtID

#9596 Enable permissions automation for group settings APIs
  api-reference/beta/api/directorysetting-delete.md
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/api/group-list-settings.md
  api-reference/beta/api/group-post-settings.md
  api-reference/beta/includes/permissions/group-post-settings-2-permissions.md
  api-reference/v1.0/api/group-list-settings.md
  api-reference/v1.0/api/group-post-settings.md
  api-reference/v1.0/api/groupsetting-delete.md
  api-reference/v1.0/api/groupsetting-get.md
  api-reference/v1.0/api/groupsetting-update.md
  api-reference/v1.0/includes/permissions/group-post-settings-2-permissions.md
Labels: area: Entra, area: groups, do not merge

#9592 Fixed evolvable enum links
  api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
  api-reference/beta/api/authenticationstrengthroot-post-policies.md
  api-reference/beta/resources/authenticationmethodmodedetail.md
  api-reference/beta/resources/driveprotectionunit.md
  api-reference/beta/resources/networkaccess-networkaccesstraffic.md
  api-reference/beta/resources/restrictaccessaction.md
  api-reference/beta/resources/restrictaccessactionbase.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/authenticationmethodmodedetail.md
  api-reference/v1.0/resources/restrictaccessaction.md
  api-reference/v1.0/resources/restrictaccessactionbase.md
Labels: content review complete, ready to merge

#9600 Clarify supported OData params for Group deltas
  api-reference/beta/api/group-delta.md
  api-reference/v1.0/api/group-delta.md
Labels: area: change tracking, area: Entra, ready to merge

#9603 Fixed type formatting
  api-reference/beta/resources/cloudpcscopedpermission.md
  api-reference/beta/resources/security-submissionresult.md
  api-reference/beta/resources/serviceupdatemessage.md
  api-reference/v1.0/api/contenttype-associatewithhubsites.md
  api-reference/v1.0/api/driveitem-invite.md
  api-reference/v1.0/api/permission-grant.md
Labels: content review complete, ready to merge

#9590 Update chatmessage-post.md
  api-reference/v1.0/api/chatmessage-post.md
Labels: content review complete, customer support issue, ready to merge

#9610 Fix Inconsistent Parameter Naming and missing {userPrincipalName} in Microsoft Graph Contacts APIs
  api-reference/v1.0/api/contact-delta.md
  api-reference/v1.0/api/contact-permanentdelete.md
Labels: content review complete, ready to merge

#9611 Fixed boilerplate sentences
  api-reference/beta/api/conversation-delete.md
  api-reference/beta/api/openshiftchangerequest-approve.md
  api-reference/beta/api/security-fileplanreferencetemplate-get.md
  api-reference/beta/api/unifiedstoragequota-get.md
  api-reference/v1.0/api/rangesort-apply.md
  api-reference/v1.0/api/tablecollection-add.md
Labels: content review complete, ready to merge

#9609 updated device threshold
  includes/throttling-device-operation.md
Labels: area: directory management, area: Entra, area: throttling, content review complete

#9615 Update planneruser-list-tasks.md
  api-reference/v1.0/api/planneruser-list-tasks.md
Labels: content review complete, ready to merge

#9614 Fixed usage of "Deletes" as a description in API topics
  api-reference/beta/api/dynamics-customerpayment-delete.md
  api-reference/beta/api/dynamics-paymentterms-delete.md
  api-reference/beta/api/dynamics-taxarea-delete.md
  api-reference/beta/api/itempublication-delete.md
  api-reference/beta/api/permissiongrantpolicy-delete-excludes.md
  api-reference/beta/api/personaward-delete.md
  api-reference/beta/api/trustframeworkpolicy-delete.md
  api-reference/beta/resources/dynamics-item.md
  api-reference/beta/resources/dynamics-unitsofmeasure.md
  api-reference/beta/resources/itempatent.md
  api-reference/beta/resources/personaward.md
  api-reference/beta/resources/personwebsite.md
  api-reference/v1.0/api/chart-delete.md
  api-reference/v1.0/api/todotask-delete.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
Labels: content review complete, ready to merge

#9612 Update and rename appconsentrequest-filterByCurrentUser.md to appcons…
  api-reference/beta/api/appconsentrequest-filterbycurrentuser.md
  api-reference/beta/includes/permissions/appconsentrequest-filterbycurrentuser-permissions.md
Labels: content review complete, ready to merge

#9607 Update v1.0 channel-getallretainedmessages.md
  api-reference/v1.0/api/channel-getallretainedmessages.md
Labels: ready to merge

#9606 Update channel-getallretainedmessages.md
  api-reference/beta/api/channel-getallretainedmessages.md
Labels: ready to merge
