Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-05, with the labels that each got.

#9562 Update unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-get.md
Labels: content review complete

#9568 Update recyclebin-list-items to use filestorage example because site RB APIs are not supported in v1.0
  api-reference/v1.0/api/recyclebin-list-items.md
Labels: ready to merge

#9570 Removing platform limits from documentation
  concepts/connecting-external-content-api-limits.md
Labels: content review complete

#9566 Remove Delve on Update social-intel-concept-overview.md
  concepts/social-intel-concept-overview.md
Labels: content review complete, ready to merge

#9569 Update driveitem-assignsensitivitylabel.md
  api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
Labels: content review complete, ready to merge

#9571 Update employeeexperienceuser.md for minor fix
  api-reference/beta/resources/employeeexperienceuser.md
Labels: content review complete, ready to merge
