Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-09, with the labels that each got.

#9649 Add deprecation disclaimer to teamworkDeviceOperations list
  api-reference/beta/api/teamworkdeviceoperation-list.md
Labels: ready to merge

#9650 Add deprecation disclaimers to teamworkDeviceActivity
  api-reference/beta/resources/teamworkdeviceactivity.md
Labels: ready to merge

#9651 Update teamworkdeviceactivity-get.md
  api-reference/beta/api/teamworkdeviceactivity-get.md
Labels: ready to merge

#9653 Update teamworkDeviceConfiguration GET documentation
  api-reference/beta/api/teamworkdeviceconfiguration-get.md
Labels: ready to merge

#9654 Add deprecation disclaimer to teamworkDeviceHealth.md
  api-reference/beta/resources/teamworkdevicehealth.md
Labels: ready to merge

#9657 Add beta deprecation disclaimer to documentation
  api-reference/beta/resources/teamworkdeviceoperation.md
Labels: ready to merge

#9661 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: content review complete, ready to merge

#9663 Update adminwindowsupdates-post-deployments.md
  api-reference/beta/api/adminwindowsupdates-post-deployments.md
Labels: ready to merge

#9669 Update driveitem-copy.md with cross-geo copy info
  api-reference/v1.0/api/driveitem-copy.md
Labels: content review complete, customer support issue

#9670 Update driveitem-copy.md with cross-geo copy info (Beta)
  api-reference/beta/api/driveitem-copy.md
Labels: content review complete, customer support issue, ready to merge

#9677 Update intune-onboarding-deviceenrollmentnotificationconfiguration.md
  api-reference/beta/resources/intune-onboarding-deviceenrollmentnotificationconfiguration.md
Labels: ready to merge

#9678 Updated What's new topic
  concepts/whats-new-overview.md
Labels: content review complete, ready to merge
