Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-03, with the labels that each got.

#9524 Update signinactivity.md
  api-reference/beta/resources/signinactivity.md
  api-reference/v1.0/resources/signinactivity.md
Labels: area: Entra, area: reports, content review complete

#9525 Fix socketio sample
  api-reference/v1.0/api/subscriptions-socketio.md
Labels: area: change notifications, area: Entra

#9528 Apply PR #9525 changes to beta
  api-reference/beta/api/subscriptions-socketio.md
Labels: do not merge

#9529 Include displayName maximum length requirment. Update certificatebasedauthpki.md
  api-reference/beta/resources/certificatebasedauthpki.md
Labels: area: Entra

#9530 Add an additional permission that is required
  api-reference/beta/api/group-delete-approleassignments.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/beta/includes/permissions/group-delete-approleassignments-permissions.md
  api-reference/beta/includes/permissions/group-post-approleassignments-permissions.md
  api-reference/v1.0/api/group-delete-approleassignments.md
  api-reference/v1.0/api/group-post-approleassignments.md
  api-reference/v1.0/includes/permissions/group-delete-approleassignments-permissions.md
  api-reference/v1.0/includes/permissions/group-post-approleassignments-permissions.md
Labels: area: Entra, area: permissions, awaiting internal response

#9535 368370 PowerShell rebrand
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/internaldomainfederation.md
Labels: area: Entra, content review complete, ready to merge
