Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-08, with the labels that each got.

#9619 Fixed typo in read only
  api-reference/v1.0/resources/appscope.md
  api-reference/v1.0/resources/groupmembers.md
  api-reference/v1.0/resources/insights-used.md
  api-reference/v1.0/resources/singleuser.md
  api-reference/v1.0/resources/teamstab.md
Labels: content review complete, ready to merge

#9617 Update planner-overview.md
  api-reference/v1.0/resources/planner-overview.md
Labels: content review complete, customer support issue, ready to merge

#9586 Update plannerapprovalrequirement.md to reflect that approval req's cannot be created programmatically
  api-reference/beta/resources/plannerapprovalrequirement.md
Labels: ready to merge

#9623 fix incorrect possible values
  api-reference/beta/api/intune-apps-win32lobapp-create.md
Labels: ready to merge

#9627 Update authenticationrequirementPolicies defination.md
  api-reference/beta/resources/signin.md
Labels: ready to merge

#9629 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: content review complete, ready to merge

#9642 Clarify description of ruleDestination resource
  api-reference/beta/resources/networkaccess-ruledestination.md
Labels: ready to merge

#9641 Update teams-licenses.md
  concepts/teams-licenses.md
Labels: content review complete, ready to merge

#9643 Update deprecation notice for filterByCurrentUser
  api-reference/v1.0/api/accesspackage-filterbycurrentuser.md
Labels: area: Entra, area: governance, content review complete, ready to merge

#9646 Update permissions comments in authentication-get.md
  api-reference/beta/api/authentication-get.md
Labels: area: Entra, ready to merge

#9625 Update todotask.md
  api-reference/v1.0/resources/todotask.md
  concepts/todo-concept-overview.md
Labels: ready to merge
