Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-01, with the labels that each got.

#9493 Updated auth-limit-mailbox-access.md to fix a broken anchor link
  concepts/auth-limit-mailbox-access.md
Labels: content review complete, ready to merge

#9494 Clarifies that `$filter` is supported on `trustType` property
  api-reference/beta/resources/device.md
  api-reference/v1.0/resources/device.md
Labels: area: Entra

#9495 Update authorizationpolicy-update.md
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/v1.0/api/authorizationpolicy-update.md
Labels: area: Entra, content review complete, ready to merge

#9499 Cover application permissions in group lookup
  concepts/permissions-overview.md
Labels: area: Entra, area: permissions

#9502 [Content Freshness] Updating auth-register-app-v2 & authenticationmethods-get-started
  concepts/auth-register-app-v2.md
  concepts/authenticationmethods-get-started.md
Labels: area: Entra, content review complete, ready to merge

#9506 Correct admin roles for profile photo edits.
  api-reference/beta/api/profilephoto-delete.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/v1.0/api/profilephoto-delete.md
  api-reference/v1.0/api/profilephoto-update.md
  concepts/profilephoto-configure-settings.md
Labels: content review complete, ready to merge
