Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-06, with the labels that each got.

#9556 As verified, app permission is fine with invitation restriction now
  api-reference/beta/api/invitation-post.md
  api-reference/v1.0/api/invitation-post.md
Labels: area: Entra, ExtID, content review complete, ready to merge

#9574 Update user-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: Entra, area: users, ready to merge

#9581 Update overview.md
  concepts/overview.md
Labels: ready to merge

#9587 Fix typos in "Advanced query capabilities on Microsoft Entra ID objects" documentation
  concepts/aad-advanced-queries.md
  includes/snippets/powershell/v1/aad-advanced-queries-get-users-not-acountenabled-powershell-snippets.md
Labels: ready to merge
