Repository microsoftgraph/microsoft-graph-docs-contrib, pull requests merged in 2025-02, with the labels that each got.

#9508 Update changenotifications-for-emergencycalls.md
  concepts/changenotifications-for-emergencycalls.md
Labels: content review complete, ready to merge

#9507 Update data-connect-troubleshooting.md
  concepts/data-connect-troubleshooting.md
Labels: content review complete, ready to merge

#9497 Update sdks-overview.md
  concepts/sdks/sdks-overview.md
Labels: changes requested, content review in progress, do not merge

#9512 Correct admin roles for people admin settings
  api-reference/beta/api/peopleadminsettings-get.md
  api-reference/beta/api/peopleadminsettings-list-profilecardproperties.md
  api-reference/beta/api/peopleadminsettings-post-profilecardproperties.md
  api-reference/beta/api/profilecardproperty-delete.md
  api-reference/beta/api/profilecardproperty-get.md
  api-reference/beta/api/profilecardproperty-update.md
  api-reference/v1.0/api/peopleadminsettings-get.md
  api-reference/v1.0/api/peopleadminsettings-list-profilecardproperties.md
  api-reference/v1.0/api/peopleadminsettings-post-profilecardproperties.md
  api-reference/v1.0/api/profilecardproperty-delete.md
  api-reference/v1.0/api/profilecardproperty-get.md
  api-reference/v1.0/api/profilecardproperty-update.md
  concepts/pronouns-configure-pronouns-availability.md
Labels: content review complete, ready to merge

#9510 Update context for US Gov
  concepts/deployments.md
Labels: content review complete, ready to merge

#9509 Update applications-authenticationbehaviors.md
  concepts/applications-authenticationbehaviors.md
Labels: content review complete, ready to merge

#9487 Bookmarks Official Doc - "Platforms" Parameter update
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/v1.0/api/search-searchentity-post-bookmarks.md
Labels: content review complete, ready to merge

#9517 chore: Delete ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: content review complete, ready to merge

#9515 approvalitem-cancel: clarify detail on who can use api
  api-reference/beta/api/approvalitem-cancel.md
Labels: content review complete, ready to merge

#9516 Update signinactivity.md
  api-reference/v1.0/resources/signinactivity.md
Labels: ready for content review

#9521 update link for recommended Sentinel API
  api-reference/beta/resources/tiindicator.md
Labels: ready to merge

#9520 Update tutorial-lifecycle-workflows-set-employeeleavedatetime.md
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: ready to merge

#9522 Update installation.md
  concepts/cli/installation.md
Labels: ready to merge
